export const testData = [
    {
        id: 0,
        name: "Maximillian",
        position: "Leading specialist of the Control Department",
        email: "controldepartment@gmail",
        phone: "+380 50 678 03 24",
    },
    {
        id: 1,
        name: "Adolph Blaine Charles David Earl Matthew Matthew",
        position: "Contextual advertizing specialist",
        email: "adolph.blainecharles@...",
        phone: "+380 50 678 03 24",
    },
    {
        id: 2,
        name: "Elizabeth",
        position: "Frontend developer",
        email: "elizabet.front@gmail.com",
        phone: "+380 50 678 03 24",
    },
    {
        id: 3,
        name: "Alexander",
        position: "Leading specialist of the Control Department",
        email: "controldepartment@gmail",
        phone: "+380 50 678 03 24",
    },
    {
        id: 4,
        name: "Noah",
        position: "Contextual advertizing specialist",
        email: "adolph.blainecharles@...",
        phone: "+380 50 678 03 24",
    },
    {
        id: 5,
        name: "Liamgrievescasey",
        position: "Frontend developer",
        email: "elizabet.front@gmail.com",
        phone: "+380 50 678 03 24",
    },
    {
        id: 6,
        name: "Alexander",
        position: "Leading specialist of the Control Department",
        email: "controldepartment@gmail",
        phone: "+380 50 678 03 24",
    },
    {
        id: 7,
        name: "Noah",
        position: "Contextual advertizing specialist",
        email: "adolph.blainecharles@...",
        phone: "+380 50 678 03 24",
    },
    {
        id: 8,
        name: "Liamgrievescasey",
        position: "Frontend developer",
        email: "elizabet.front@gmail.com",
        phone: "+380 50 678 03 24",
    }
];
